### ISSUE TITLE
[IDEA] Update Rhino javascript engine to the latest version

### ISSUE THREAD

**Issue by araxor** [OpenIntegrationEngine/engine#257]
**Is your feature request related to a problem? Please describe.**
Open Integration Engine currently ships with Rhino 1.7.13 (released September 2020), which has limited support for modern JavaScript (ES2015+) features. This makes writing and maintaining channel scripts unnecessarily difficult, as developers cannot use common modern JS syntax such as template literals, arrow functions, destructuring, `Object.entries()`/`Object.values()`, and many other widely adopted language features.

**Describe your use case**
I need modern JavaScript features (ES2015/ES2016/ES2017+) to write cleaner, more maintainable channel scripts. Rhino 1.7.13 only covers roughly 42% of ES2015 and 22% of ES2016+, while newer Rhino releases significantly expand that coverage. Being able to use features like template literals, `const`/`let`, arrow functions, and modern Array/Object methods would greatly improve the developer experience.

**Describe the solution you'd like**
Update the bundled Rhino engine from 1.7.13 to the latest available version (currently 1.9.1 as of February 2026). The Rhino compatibility table at https://mozilla.github.io/rhino/compat/engines.html shows substantial ES2015/ES2016/ES2017 improvements with each major version bump (1.7.14, 1.7.15, 1.8.x, and 1.9.x). Note that Rhino 1.8+ requires Java 11 or higher to run.

**Describe alternatives you've considered**
- **Manually replacing the Rhino JAR**: This may or may not work as a drop-in replacement, since the engine is tightly coupled with the codebase (E4X support, script compilation, `rhino.languageversion` property, etc.). Mirth Connect itself had to handle regressions in the past when upgrading Rhino (see [nextgenhealthcare/connect#3838](https://github.com/nextgenhealthcare/connect/issues/3838) and [nextgenhealthcare/connect#2134](https://github.com/nextgenhealthcare/connect/issues/2134)).
- **Transpiling modern JS to ES5 before pasting into channels**: Adds complexity and makes debugging harder.
- **Replacing Rhino entirely with a different engine (e.g., V8/GraalJS)**: A much larger effort, as discussed in [nextgenhealthcare/connect#4409](https://github.com/nextgenhealthcare/connect/issues/4409). Upgrading Rhino is a more pragmatic short-term solution.

**Additional context**
- Rhino compatibility table (ES2015/ES2016/ES2017 per version): https://mozilla.github.io/rhino/compat/engines.html
- Mirth Connect (the upstream project) already performed a Rhino update to 1.7.13 in its 4.0.0 release ([wiki reference](https://github.com/nextgenhealthcare/connect/wiki/4.0.0---What's-New)), so there is precedent for this kind of upgrade.
- Rhino 1.9.1 is available on Maven Central as `org.mozilla:rhino:1.9.1`.

**Comment by tonygermano** [comment]
This is definitely a personal priority for me, but I know there are several changes required to allow newer versions of Rhino to work with the engine. A drop-in replacement will not work. I have a goal to get the code to a point where a drop-in replacement will work.

The java requirement is not a problem as we already require java 17.

Regarding features mentioned in your description, some of them are currently supported
- arrow functions: these have been around since Mirth 3.7
- destructuring: supported in assignments, but not in function parameters. You may get red squiggles in the editor, but they should validate and run. The squiggles will not go away by upgrading the rhino library. These are very handy for doing java imports.
- const: this is supported, but it has a scoping issue described [here](https://github.com/mozilla/rhino/issues/326)
- let: this is mostly supported, but does not implement the "temporal dead zone," which is not a problem in most cases. Also suffers from the red squiggle issue.

Here's a contrived example showing what currently works in OIE with Rhino 1.7.13. You can see the syntax highlighter is not happy about it. That is a separate issue to fix.

<img width="539" height="442" alt="Image" src="https://github.com/user-attachments/assets/ea0c1bca-8e51-44b1-ac10-a32da4e0352b" />
